name: deploy

on:
  workflow_run:
    workflows: [documentation, coverage, nightly_tests]
    types: [completed]
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == '4C-multiphysics/4C'
      }}
    steps:
      - uses: dawidd6/action-download-artifact@v12
        with:
          workflow: documentation.yml
          name: doxygen
          path: ${{ github.workspace }}/doxygen
          branch: ${{ github.event.repository.default_branch }}
      - uses: dawidd6/action-download-artifact@v12
        with:
          workflow: documentation.yml
          name: documentation
          path: ${{ github.workspace }}/documentation
          branch: ${{ github.event.repository.default_branch }}
      - uses: dawidd6/action-download-artifact@v12
        with:
          workflow: coverage.yml
          name: 4C_coverage_report
          path: ${{ github.workspace }}/coverage_report
          branch: ${{ github.event.repository.default_branch }}
      - uses: dawidd6/action-download-artifact@v12
        with:
          workflow: nightly_tests.yml
          name: clang18_compile_time_report
          path: ${{ github.workspace }}
          branch: ${{ github.event.repository.default_branch }}
      - uses: actions/upload-pages-artifact@v4
        id: deployment
        with:
          path: ${{ github.workspace }}
          retention-days: 1
      - uses: actions/deploy-pages@v4

